### ISSUE TITLE
L1 and L2 Weight Files Throwing Pytorch Error

### ISSUE THREAD

**Issue by alan-smith-vt** [beric7/corrosion_cs_classification#1]
While the "resnet" weights and "wbatch" weights work fine, attempting to load the "l1_loss "or "l2_loss" weights throws a pytorch version error.

The specific line of code can be seen in line 15 in "run_show_results__.py" where it calls:
model = torch.load('filePath',map_location=torch.devce('cuda'))

The error is "Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation my be too old. 

My versions for PyTorch and Torchvision are 1.4.0 and 0.5.0 respectively.

![image](https://user-images.githubusercontent.com/48192097/159811532-34784fba-c7a4-4691-b401-0659a53573ee.png)

**Comment by beric7** [comment]
Alan, can you verify that this is fixed?
