### ISSUE TITLE
unable to run the code

### ISSUE THREAD

**Issue by Syna-20** [beric7/corrosion_cs_classification#2]
the command python main_plus.py -data_directory '/PATH TO DATA DIRECTORY/' -exp_directory '/PATH TO SAVE CHECKPOINTS/' \
--epochs 40 --batch 2   is not running and giving lots of errors
could you please let me know the right way to run?
![image](https://user-images.githubusercontent.com/101783446/213929837-147c4631-5500-4b93-b783-050a4407b5c6.png)
 this is the error I am getting.

**Comment by beric7** [comment]
There could be many issues. Could you try running the However, I am planning on refactoring the repo in a month or so.

**Comment by beric7** [comment]
Is it failing on line 51 of main_plus.py? Or some place else. 

How are you running the code? By command line, right?

Are you in a python env like anaconda or pip env? 

What inputs are you giving it? Have you downloaded a model, or are you training from scratch?

**Comment by Syna-20** [comment]
> Is it failing on line 51 of main_plus.py? Or some place else.
> 
> How are you running the code? By command line, right?
> 
> Are you in a python env like anaconda or pip env?
> 
> What inputs are you giving it? Have you downloaded a model, or are you training from scratch?

No ,I am not using anaconda or env. I have Python 3.7 installed. At first I tried on cmd, then the same error was being shown on Vs code as well.
You can see the above snapshot attached, with the exact error.
I ried running with pre trained model as well



when I am running the run_metrics_evaluation,py
![image](https://user-images.githubusercontent.com/101783446/213979224-4399116d-1adb-4ab6-aa51-42de30c90ba0.png)
the above image shows the error

![image](https://user-images.githubusercontent.com/101783446/213987935-5c0c145c-3ecb-4f0b-b4cf-96c262f181c2.png)
this is the next error.

**Comment by beric7** [comment]
There are several issues. 
1. you are using a CPU
2. it appears to not be able to read the image that you are referencing, i.e. a NoneType when trying to get the shape of the image. 
3. you should really be using a conda env when setting up these projects.
