### ISSUE TITLE
512x512 dataset issue

### ISSUE THREAD

**Issue by justOleh** [beric7/corrosion_cs_classification#4]
First of all, thank you for your work. There is no publicly available dataset in the wild. 
Let me just point you to one issue in your 512x512 images test set is the same as the train set. 
Just to keep in mind during training.

**Comment by beric7** [comment]
@justOleh Thank you for raising your concern. The dataset is correct. You may be looking at an older version (1). When I originally uploaded the dataset to the digital library, it was not correct, but I corrected my error shortly. Please use the most recent version of the dataset (version 2).
